name: xnd-env
channels:
  - conda-forge
  - xnd/label/dev
  - QuantStack
  - defaults

dependencies:
  - python==3.6
  - numpy
  - gumath
  - xnd
  - numba
  - jupyterlab_launcher>=0.5.0
  - xeus-cling

